### ISSUE TITLE
Cannot load checkpoints

### ISSUE THREAD

**Issue by rcao-hk** [MRUIL/LoViT#2]
Hi, 

Thank you for your work!

When I load the checkpoint, the error throws: "ModuleNotFoundError: No module named 'timm.models.layers.patch_embed'". Maybe you use an old version of timm. Could you please define the model by a python file? Thank you.

Best,
Rui

**Comment by MRUIL** [comment]
Hi Rui,

Thanks for your question. It's my fault, I didn't upload the TIMM code which caused some bugs. It has been updated now. If you still have any questions, please let me know.

**Comment by rcao-hk** [comment]
> Hi Rui,
> 
> Thanks for your question. It's my fault, I didn't upload the TIMM code which caused some bugs. It has been updated now. If you still have any questions, please let me know.

Hi,

It still throw the error: `ModuleNotFoundError: No module named 'timm.models.layers.patch_embed' ` 

My script is
`import torch`
`model = torch.load('Trained_VIT_Cholec80.pth')`

And my timm version is 0.9.12. Could you please share your timm version? I guess this due to the different version of timm.

Best,
Rui

**Comment by MRUIL** [comment]
Hi Rui,

My timm version is 0.4.12, I will clarify it.
